- hosts: localhost
  gather_facts: no
  become: true
  vars:
    cluster_name: "ccw"
    ood_cluster_dir: "/shared/ood/config/clusters.d"
    bin_overrides_dir: "{{ood_cluster_dir}}/slurm_{{cluster_name}}/bin_overrides"

  tasks:
  - name: Wait 300 seconds for the nodes to be ready
    wait_for_connection:
      timeout: 300
  - name: Gather facts for first time
    setup:

  - name: install jq
    ansible.builtin.package:
      name: jq
      state: present

  - name: Get the CycleCloud username
    shell: |
      jetpack config cyclecloud.config.username
    register: cyclecloud_username

  - name: get the CycleCloud password
    shell: |
      jetpack config cyclecloud.config.password
    register: cyclecloud_password

  - name: Get the CycleCloud URL
    shell: |
      jetpack config cyclecloud.config.web_server
    register: cyclecloud_url  
  
  - name: Retrieve the node list
    shell: |
      curl -k -u {{ cyclecloud_username.stdout }}:{{ cyclecloud_password.stdout }} {{ cyclecloud_url.stdout }}/clusters/{{ cluster_name }}/nodes > /tmp/{{ cluster_name }}.json
    
  - name: Retrieve the login nodes
    shell: |
      jq '.nodes[] | select(.Status=="Ready") | select(.Template=="login") | .Hostname' /tmp/{{ cluster_name }}.json
    register: login_node

  - name: Retrieve the scheduler node
    shell: |
      jq '.nodes[] | select(.Status=="Ready") | select(.Template=="scheduler") | .Hostname' /tmp/{{ cluster_name }}.json
    register: scheduler

  - name: debug
    debug:
      msg: 
        - "{{ login_node.stdout }}"
        - "{{ scheduler.stdout }}"
        - "{{ node_list.stdout }}"

  - name: Copy the bin overrides
    ansible.builtin.file:
      src: "{{ item }}"
      dest: "{{ bin_overrides_dir }}/{{ item | basename }}"
      mode: '0755'
    loop:
      - files/slurm/sbatch.sh
      - files/slurm/squeue.sh
      - files/slurm/scontrol.sh
      - files/slurm/scancel.sh
      - files/slurm/sinfo.sh
      - files/slurm/sacctmgr.sh

  - name: Copy the slurm proxy script
    ansible.builtin.template:
      src: slurm_proxy.sh.j2
      dest: "{{ bin_overrides_dir }}/slurm_proxy.sh"
      mode: '0755'

  - name: Create the cluster configuration file
    ansible.builtin.template:
      src: slurm_cluster.yml.j2
      dest: "{{ ood_cluster_dir }}/slurm_{{ cluster_name }}.yml"
      mode: '0644'

  - name: Create the login configuration file
    ansible.builtin.template:
      src: login_cluster.yml.j2
      dest: "{{ ood_cluster_dir }}/login_slurm_{{ cluster_name }}.yml"
      mode: '0644'