---
ood_apps:
  dashboard:
    env:
      ood_bc_dynamic_js: true

host_regex: '[^./]+'
node_uri: '/node'
rnode_uri: '/rnode'
pun_pre_hook_root_cmd: /etc/ood/config/pun_pre_hook.sh
cancel_session_enabled: true

# Hide spurious alert-undefined elements from widgets that fail to load
custom_css_files: ["/custom.css"]

# This is to support SSL reverse proxy for ThinLinc
secure_rnode_uri: '/secure-rnode'
ssl_proxy:
  - 'SSLProxyCheckPeerCN Off'
  - 'SSLProxyCheckPeerName Off'

pun_custom_env:
  OOD_DASHBOARD_TITLE: "Open OnDemand with Azure CycleCloud"
  OOD_BRAND_BG_COLOR: "#0078d4"
  OOD_BRAND_LINK_ACTIVE_BG_COLOR: "#212529"
  OOD_JOB_NAME_ILLEGAL_CHARS: "/"
  OOD_SHELL_PING_PONG: true
  OOD_QUOTA_PATH: "/etc/ood/config/quota.json"
  OOD_QUOTA_THRESHOLD: "0.95"

# See https://osc.github.io/ood-documentation/latest/customization.html#pinning-applications-to-the-dashboard
pinned_apps_group_by: category
pinned_apps:
  - sys/shell
  - category: 'Interactive Apps'

# See https://osc.github.io/ood-documentation/latest/customizations.html#custom-layouts-in-the-dashboard
dashboard_layout:
  rows:
    - columns:
      - width: 8
        widgets:
          - pinned_apps
          - sessions
      - width: 4
        widgets:
          - file_quotas
          - system_status
