---
- name: Copy application files
  copy:
    src: '{{role_path}}/files/{{ item.name }}'
    dest: /var/www/ood/apps/sys/
    mode: 0755
  loop:
    - { name: 'connect_cluster' }

  # Fix permissions for the Ansible directory, so the vars.yml file can be written
  - name: Fix permissions
    ansible.builtin.file:
      path: /var/www/ood/apps/sys/connect_cluster/Ansible
      mode: '0777'
      state: directory

  # Fix permissions for the CycleCloud Connect directory
  - name: Fix permissions
    ansible.builtin.file:
      path: /var/www/ood/apps/sys/connect_cluster/
      mode: '0773' # Owner RWX, Group RWX, Public --X this limits it only to root and users in the cyclecloud admin group
      owner: 'root'
      group: 'cyclecloud'
      state: directory

  - name: Initialize application
    file:
      path: /var/lib/ondemand-nginx/config/apps/sys/connect_cluster.conf
      state: touch

  - name: Use Python3 wrapper for passenger apps
    lineinfile:
      state: present
      dest: /etc/ood/config/nginx_stage.yml
      regexp: "^#passenger_python|^passenger_python"
      line: "passenger_python: '/mnt/cluster-init/ood/default/files/python_wrapper.sh'"

  - name: update nginx stage
    shell: |
      /opt/ood/nginx_stage/sbin/update_nginx_stage &>/dev/null || :
